/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_Acciones */

#ifndef _Included_org_example_Acciones
#define _Included_org_example_Acciones
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_Acciones
 * Method:    CompilarYEjecutar
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_example_Acciones_CompilarYEjecutar
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
